services:
  - type: web
    name: django-app
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn hospital_management.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: hospital_management.settings  # FIXED path
      - key: PYTHON_VERSION
        value: 3.11
      - key: DEBUG
        value: "False"
