services:
  - type: web
    name: django-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hospital_management.wsgi.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: hospital_management.wsgi.settings
      - key: PYTHON_VERSION
        value: 3.11
